### PR TITLE
feat: add new attributes

### PR DESCRIPTION
**Pull request by arunsudhakar**
Added new attributes : 

**Latitude/Longitude** - So that location can be shown on map 
**Disruptions** - Shows the text of any active disruptions 
**Stopping At Destination** - Added option to add destination stop, so as to cater for trains which dont stop at those stations

image

When combined with mushroom template card, it can be displayed like this

image

Happy to share the code of the mushroom template as well

### CODE REVIEW

**Comment by arunsudhakar** [comment]
@bremor Can you please help review and commit if you are ok with it?

**Comment by catatonicChimp** [comment]
hey @arunsudhakar can you confirm you've tested the upgrade path on the updates? my brief testing this arvo had my entities breaking when I upgraded, we should make sure that we don't break existing configs on updates unless its warranted. 

`2024-10-05 18:45:33.642 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Upfield line to City (Flinders Street) from Coburg Station for public_transport_victoria
Traceback (most recent call last):
  File "/Users/ataylor/Development/ha_core/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ataylor/Development/ha_core/config/custom_components/public_transport_victoria/__init__.py", line 34, in async_setup_entry
    entry.data[CONF_DESTINATION_STOP],
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'destination_stop'`

**Comment by arunsudhakar** [comment]
@catatonicChimp  - Let me have a look into that. I'll create another PR using v 0.6 as the base and incorporate and test the changes into that. Need to add some functionality too

**Comment by catatonicChimp** [comment]
Hey @arunsudhakar 

just to let you know I am in progress of refactoring the whole API connector, still a few more weekends work (assuming I find time) but it will include far easier ways of pulling the live location data and things like which stations its stopping at, and disruption data...

Just thought I should let you know in case you are working on the above, as you might want to hold back for a little bit.

**Comment by arunsudhakar** [comment]
Oh ok..thanks for letting me know..I'll hold back on my work or I can
contribute if required (time permitting).

**Pull request closed without merging**
