### PR TITLE
Replace device_state_attributes with extra_state_attributes

### PR DESCRIPTION
**Pull request by kaizersoje**
remove device_state_attributes deprecation warnings in latest HA versions

### CODE REVIEW

**Comment by kaizersoje** [comment]
Fixed #8 by adding attribution

**Comment by kaizersoje** [comment]
Hi @bremor, have you had a chance to look at this?

**Comment by bremor** [comment]
Thanks @kaizersoje I have merged your request and will create a new release.

**Comment by kaizersoje** [comment]
No worries :)

**Pull request merged**
